### ISSUE TITLE
Error: Not connected to Bluetooth

### ISSUE THREAD

**Issue by dcockerton** [rrrlasse/powerino#1]

**Comment by rrrlasse** [comment]
Is the phone actually connected to the powermeter? If you swipe twice to the left, to the debugging screen, what does it say for the sample rate?

**Comment by jura38** [comment]
i can not calibrate  only goin to start

**Comment by jura38** [comment]
hi .. my you say me  why  i have negative  w  last 30 sec         rpm is positive .   and what i may make to fastest change  actual power on  display . ?      I  program last version app .

                                                                                               thank ypu

**Comment by rrrlasse** [comment]
@jura38 The wattage can show up as negative for a brief period whenever the left pedal arm is being lifted by pressing the right pedal arm down (so that the "kg" indicator is negative).

It's just a mathematical method to make it take both pedal arms in count even though it's a left-only power meter.

The screen updates each second and can't be changed (unless you install Android Studio and re-compile the program - this is actually pretty simple). The scroll wheel selects how many seconds to average over, for the "current wattage"

**Comment by jura38** [comment]
thank you
 I solved the problem of negative average strength. The problem was that I calibrated the powermetar in an improper manner. And the power and the average power were negative. It is clear that the weight has a positive and negative comonomer depending on the direction.

 I do not have a clear label of 1-30 but now everything is clear ..

I do this for a supper by putting the gouge of life span
10 000 000 bending

**Comment by jura38** [comment]
hi .
 Have you idea to inplementation    heart rate     monitor in android program   , and heave possibility  connecting two  ble  device  . One  from powermeter  an second from   heart rate  ble  senzor ..

**Comment by rrrlasse** [comment]
@jura38 it should be possible to connect to two BLE devices. The heart rate protocol is described here https://developer.android.com/guide/topics/connectivity/bluetooth-le

**Comment by jura38** [comment]
ooo   for mee  android studio  is nasa project ,,

**Comment by Stroker80** [comment]
@mrlasse I have the same issue "_Not connected to Bluetooth_", the device is paired but when I'm going to calibrate and touch in "start" it shows the "_Not connected to Bluetooth_".
I tried with another smartphone and the old apk, but itś the same.
Thanks a lot for sharing this project.
